"""add mileage settings

Revision ID: 326895ef4690
Revises: 7872fc9f8179
Create Date: 2026-08-30 17:51:36.091585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '326895ef4690'
down_revision: Union[str, Sequence[str], None] = '7872fc9f8179'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mileage_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workplace', sa.String(length=200), nullable=False),
    sa.Column('mileage', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workplace')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mileage_settings')
    # ### end Alembic commands ###
