"""Add fuel consumption allocations

Revision ID: de1da632d7d3
Revises: 05e7ee6af3d2
Create Date: 2026-09-11 15:55:11.261693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de1da632d7d3'
down_revision: Union[str, Sequence[str], None] = '05e7ee6af3d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fuel_consumption_allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('daily_report_id', sa.Integer(), nullable=False),
    sa.Column('fuel_batch_id', sa.Integer(), nullable=False),
    sa.Column('liters', sa.Float(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['daily_report_id'], ['daily_reports.id'], ),
    sa.ForeignKeyConstraint(['fuel_batch_id'], ['fuel_batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fuel_consumption_allocations')
    # ### end Alembic commands ###
