"""add daily reports

Revision ID: e0f319d84e93
Revises: 326895ef4690
Create Date: 2026-08-30 20:14:40.618978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0f319d84e93'
down_revision: Union[str, Sequence[str], None] = '326895ef4690'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('workplace', sa.String(length=100), nullable=False),
    sa.Column('mileage', sa.Float(), nullable=False),
    sa.Column('refueled', sa.Boolean(), nullable=False),
    sa.Column('fuel_liters', sa.Float(), nullable=True),
    sa.Column('fuel_amount', sa.Float(), nullable=True),
    sa.Column('work_description', sa.String(length=200), nullable=False),
    sa.Column('work_completed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('daily_reports')
    # ### end Alembic commands ###
