"""add fuel fields to daily reports

Revision ID: f3f6adc240d6
Revises: d0c2cdd3952d
Create Date: 2026-09-11 14:46:54.838650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3f6adc240d6'
down_revision: Union[str, Sequence[str], None] = 'd0c2cdd3952d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fuel_consumption_rate', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('fuel_consumed', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_reports', schema=None) as batch_op:
        batch_op.drop_column('fuel_consumed')
        batch_op.drop_column('fuel_consumption_rate')

    # ### end Alembic commands ###
